default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Teste123 # Coloque a mesma senha aqui
  host: 127.0.0.1

development:
  <<: *default
  database: katathesi_development # Nome do banco de dados atualizado

test:
  <<: *default
  database: katathesi_test # Nome do banco de dados atualizado

production:
  <<: *default
  database: katathesi_production # Nome do banco de dados atualizado
  username: katathesi # Usuário específico para produção, se houver
  password: <%= ENV["Kteste123"] %> # Variável de ambiente para a senha de produção
